FROM ruby:2.4 as build

WORKDIR /app

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install

COPY source source
COPY bin bin
COPY config.rb config.rb

ENV LC_ALL=C.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

RUN middleman build


FROM nginx:1.13-alpine

COPY --from=build /app/www /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
