source "https://rubygems.org"

gem "builder"
gem "html-proofer"
gem "middleman"
gem "middleman-blog"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-sprockets"
gem "middleman-syntax"
gem "redcarpet"
gem "therubyracer"
gem "sanitize"
